Word Embedding Techniques using Embedding Layer in Keras

In [2]:
### Libraries USed Tensorflow> 2.0  and keras

In [4]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
##vocabulary size
voc_size=500 #larger the size the the features but processing time will be more

# One Hot Representation

In [20]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)
#this will return the value of indices of words from sent in the voc size (here, 10000) 

[[366, 298, 13, 224], [366, 298, 13, 477], [366, 486, 13, 352], [339, 314, 47, 323, 240], [339, 314, 47, 323, 436], [372, 366, 399, 13, 52], [154, 111, 295, 323]]


# Word Embedding Representation

In [21]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [23]:
## pre padding
sent_length=8 #set the maximum sentence length so that the dimension/shape of the onehot_repr becomes equal i.e of 8 instead of varying size like 4,5 etc.
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) #padding=pre means add 0s before the nos.
print(embedded_docs) 

[[  0   0   0   0 366 298  13 224]
 [  0   0   0   0 366 298  13 477]
 [  0   0   0   0 366 486  13 352]
 [  0   0   0 339 314  47 323 240]
 [  0   0   0 339 314  47 323 436]
 [  0   0   0 372 366 399  13  52]
 [  0   0   0   0 154 111 295 323]]


In [24]:
 dim=10 #feature representation dimension=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 366, 298,  13, 224], dtype=int32)

In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 71ms/step


array([[-0.01735346,  0.00726771,  0.01174154,  0.01624891,  0.04010929,
        -0.00863708,  0.04406304, -0.01946694,  0.00828435, -0.04374932],
       [-0.01735346,  0.00726771,  0.01174154,  0.01624891,  0.04010929,
        -0.00863708,  0.04406304, -0.01946694,  0.00828435, -0.04374932],
       [-0.01735346,  0.00726771,  0.01174154,  0.01624891,  0.04010929,
        -0.00863708,  0.04406304, -0.01946694,  0.00828435, -0.04374932],
       [-0.01735346,  0.00726771,  0.01174154,  0.01624891,  0.04010929,
        -0.00863708,  0.04406304, -0.01946694,  0.00828435, -0.04374932],
       [ 0.01880721,  0.04559407, -0.00637513, -0.01792804,  0.03022779,
         0.0035167 ,  0.00193499, -0.01417316,  0.03950181,  0.03054006],
       [-0.049581  , -0.02291931,  0.04081175, -0.03456988,  0.01258175,
        -0.02930363,  0.04681965,  0.01118664, -0.03334863, -0.00157752],
       [-0.0236212 ,  0.03867127, -0.04065052,  0.02548959,  0.04413155,
         0.01683079, -0.00623187, -0.03608457

In [30]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 22ms/step
[[[-0.01735346  0.00726771  0.01174154  0.01624891  0.04010929
   -0.00863708  0.04406304 -0.01946694  0.00828435 -0.04374932]
  [-0.01735346  0.00726771  0.01174154  0.01624891  0.04010929
   -0.00863708  0.04406304 -0.01946694  0.00828435 -0.04374932]
  [-0.01735346  0.00726771  0.01174154  0.01624891  0.04010929
   -0.00863708  0.04406304 -0.01946694  0.00828435 -0.04374932]
  [-0.01735346  0.00726771  0.01174154  0.01624891  0.04010929
   -0.00863708  0.04406304 -0.01946694  0.00828435 -0.04374932]
  [ 0.01880721  0.04559407 -0.00637513 -0.01792804  0.03022779
    0.0035167   0.00193499 -0.01417316  0.03950181  0.03054006]
  [-0.049581   -0.02291931  0.04081175 -0.03456988  0.01258175
   -0.02930363  0.04681965  0.01118664 -0.03334863 -0.00157752]
  [-0.0236212   0.03867127 -0.04065052  0.02548959  0.04413155
    0.01683079 -0.00623187 -0.03608457  0.02014806  0.04575593]
  [ 0.03473357 -0.02273051  0.02382958  0.01364552 -0.02003